### ISSUE TITLE
Gmail SMTP: You can no longer use the account's password

### ISSUE THREAD

**Issue by CodeKid0** [imthenachoman/How-To-Secure-A-Linux-Server#106]
It seems that to use Gmail and Exim4 you can no longer use the account's password for SMTP authentication, even if you have 2FA disabled.
If you try to, the output of `tail /var/log/exim4/mainlog` will be similar to this:
```
plain authenticator failed H=smtp.gmail.com Username and Password not accepted. Learn more at https://support.google.com/mail/?p=BadCredentials - gsmtp
login authenticator failed H=smtp.gmail.com Username and Password not accepted. Learn more at https://support.google.com/mail/?p=BadCredentials - gsmtp
```
The solution is to enable 2FA on the account, create an App Password and use it without any spaces.

It would be nice to have that updated in the [Gmail and Exim4 As MTA With Implicit TLS](https://github.com/imthenachoman/How-To-Secure-A-Linux-Server#gmail-and-exim4-as-mta-with-implicit-tls) section.

**Comment by imthenachoman** [comment]
Good idea. I will add. A bit busy this week but will get to it.

**Comment by imthenachoman** [comment]
Fixed. Thanks!
