### ISSUE TITLE
HashKnownHosts set to yes

### ISSUE THREAD

**Issue by Kataane** [imthenachoman/How-To-Secure-A-Linux-Server#115]
Thanks for all your hard work.

I would like to clarify that nowhere did I find mention of HashKnownHosts and that it is better to set HashKnownHosts yes in ssh_config. 

This is especially important when using public keys instead of password login. For example, if a server is used as a point of entry to another server via ssh.

You can read more about this in:
[mozilla OpenSSH server](https://infosec.mozilla.org/guidelines/openssh#configuration-1). 
[mit edu about sshworm](http://nms.csail.mit.edu/projects/ssh/sshworm.pdf)
[linux-audit](https://linux-audit.com/audit-ssh-configurations-hashknownhosts-option/)
[serverfault](https://serverfault.com/questions/233855/why-should-i-use-hashknownhosts-yes-in-ssh-config)

Maybe this will be useful to someone.

**Comment by imthenachoman** [comment]
Good catch. I'll add. Thanks.

**Comment by klnstprx** [comment]
Adding this line to /etc/ssh/sshd_config does not work for me:
`sudo service sshd restart
Job for ssh.service failed because the control process exited with error code.
See "systemctl status ssh.service" and "journalctl -xeu ssh.service" for details.
`

**Comment by imthenachoman** [comment]
Maybe only some versions support the config? When I `man sshd_config`, I do not see `HashKnownHosts` as an option?

**Comment by imthenachoman** [comment]
So this is an SSH client configuration, not a SSH server configuration. It is for `/etc/ssh/ssh_config`.

**Comment by Fuckingnameless** [comment]
> So this is an SSH client configuration, not a SSH server configuration. It is for `/etc/ssh/ssh_config`.

why is the guide adding lines to the wrong config file and you have not updated it?

**Comment by landboat** [comment]
> So this is an SSH client configuration, not a SSH server configuration. It is for `/etc/ssh/ssh_config`.

This should be noted in the guide as a separate step from the other sshd_config changes to reduce confusion.

**Comment by Nesuma** [comment]
This is still part of the https://github.com/imthenachoman/How-To-Secure-A-Linux-Server?tab=readme-ov-file#secure-etcsshsshd_config

**Comment by EggEnormous** [comment]
Confirming that this is still listed as an item to change in the sshd_config, when it should be listed under ssh_config. 

For Ubuntu users, as of 24.04 the HashKnownHosts yes option is default in ssh_config.

**Comment by R1skNt** [comment]
HashKnownHosts must be removed from sshd_config in Ubuntu 24.04, otherwise the SSH service crashes
