### ISSUE TITLE
reference guides

### ISSUE THREAD

**Issue by rudolfolah** [imthenachoman/How-To-Secure-A-Linux-Server#12]
Hi, not sure if you know about this, but back in the day, The Linux Documentation Project featured some guides on [Linux system administration](https://www.tldp.org/LDP/sag/html/index.html) and also contained a [Linux Administrator's Security Guide](https://seifried.org/lasg/).

While some of the information is a little, large parts of it are still relevant.

For example, you mention disk encryption. There's a section on file system encryption: https://seifried.org/lasg/filesystem/ and it could be a good starting point.

I agree with your comment in the README:

>This guide may appear duplicative/unnecessary because there are countless articles online that tell you how to how to secure Linux but the information is spread across different articles, that cover different things, and in different ways. Who has time to scour through hundreds of articles?

I'm surprised that Google/DuckDuckGo do not rank the better guides on securing a Linux system higher, I would expect something from Red Hat, Canonical or the Linux Documentation Project to appear in the first page of the search results.

**Comment by imthenachoman** [comment]
I was not aware of those guides. I will look at them. They look seriously awesome. Not sure how I never saw them before. 

Thanks!

**Comment by francoism90** [comment]
@imthenachoman The ArchWiki provides a good guide to protect/secure Linux systems. Although it mainly focus on Arch Linux, the instructions should apply to other distro's as well.

https://wiki.archlinux.org/index.php/Security

**Comment by imthenachoman** [comment]
Added links to all of those in [#other-guides](https://github.com/imthenachoman/How-To-Secure-A-Linux-Server#other-guides). I'll also go through all of them when I have more time to see if there is anything new I should pull in.
