### ISSUE TITLE
What about Rkhunter and chrootkit

### ISSUE THREAD

**Issue by sowiso** [imthenachoman/How-To-Secure-A-Linux-Server#13]
Don't we need those?

**Comment by EvilOlaf** [comment]
My guess would be yes and no.

If someone is inside already it is often too late and the damage has been done. Either on your services or on others.
It really depends on the authors opinion to cover steps creeping up somebody that is already inside as well.
So I would consider these tools as nice-to-have but they actually do not  _prevent_ somebody from getting inside.

**Comment by imthenachoman** [comment]
Yes, I do need to add them. So much to add. Heh. I'll add to to do list. Might have time this weekend to get to it.

**Comment by imthenachoman** [comment]
I added basic details for now. I need to add some more content when I get some time.

**Comment by hellresistor** [comment]
Ressuciting this topic. This on my opinion its the same have a antivirus on a server when the server are insecured. Useful only a Samba/storage servers. To scanning the bad files uploaded by users.

**Comment by Atavic** [comment]
rkhunter has a different role.

**Comment by imthenachoman** [comment]
`rkhunter` and `chrootkit` would still make sense on samba server to catch files added by samba, no?

**Comment by imthenachoman** [comment]
Started adding something for both.
