### ISSUE TITLE
Add more tips from CIS benchmarks and Lynis auditing tool

### ISSUE THREAD

**Issue by feketegy** [imthenachoman/How-To-Secure-A-Linux-Server#15]
Links: 

1. https://www.cisecurity.org/cis-benchmarks/
2. https://cisofy.com/lynis/

**Comment by imthenachoman** [comment]
I already have a section on Lynis. I will check out and add the other. Thanks!

**Comment by imthenachoman** [comment]
So I got to looking, and I don't know if I want to copy everything from the benchmarks. The Debian one is 400 pages. Instead, I added a blurb about checking them. There is some overlap with what this guide has and what the CIS benchmarks have but I think both guides have some unique things worth checking. I'll be going through the benchmarks again and adding what I think makes the most sense to include in this guide.
