### ISSUE TITLE
UsePrivilegeSeparation deprecated since OpenSSH 7.5

### ISSUE THREAD

**Issue by soupersauce** [imthenachoman/How-To-Secure-A-Linux-Server#20]
Checking auth.log and noticed:

    sshd[58017]: rexec line 21: Deprecated option UsePrivilegeSeparation

Quick search comes up with: https://www.openssh.com/txt/release-7.5

>This release deprecates the sshd_config UsePrivilegeSeparation
   option, thereby making privilege separation mandatory. Privilege
   separation has been on by default for almost 15 years and
   sandboxing has been on by default for almost the last five.

**Comment by imthenachoman** [comment]
Interesting. I am still on 7.4. Debian is always a few versions behind. I'll add a note about that to the guide. Thanks!
