### ISSUE TITLE
Thank You

### ISSUE THREAD

**Issue by netcarver** [imthenachoman/How-To-Secure-A-Linux-Server#27]
@imthenachoman Not seeing another way to contact you to say "Thank you" for this guide, so I thought I'd post my thanks as a comment issue :)

I appreciate the time you've put into this!

**Comment by the94air** [comment]
I wouldn't be a problem, GitHub support deleting issues! :smile:

**Comment by imthenachoman** [comment]
@netcarver You are very welcome. I am glad you found it helpful. And I'm open to any/all feedback so please share if you have any.

@the94air I didn't know you could delete issues. I wouldn't do that though. :)
