### ISSUE TITLE
Hardening SSH with 2fa -lizthegrey

### ISSUE THREAD

**Issue by pahakalle** [imthenachoman/How-To-Secure-A-Linux-Server#35]
Anything in this that can/should be added
https://gist.github.com/lizthegrey/9c21673f33186a9cc775464afbdce820

**Comment by imthenachoman** [comment]
This is great. I will check and add. Thanks!

**Comment by imthenachoman** [comment]
I have added a section for 2FA at https://github.com/imthenachoman/How-To-Secure-A-Linux-Server#2famfa-for-ssh. That should cover the same thing...
