### ISSUE TITLE
Fail2Ban fails to add sshd jail

### ISSUE THREAD

**Issue by Destarianon** [imthenachoman/How-To-Secure-A-Linux-Server#36]
Using Ubuntu 18.04 when running the command
`sudo fail2ban-client add sshd`

I receive the error message:
`name 'noduplicates' is not defined`

The config file is exactly as described in the guide. All previous fail2ban commands ran successfully with no warnings.

**Comment by imthenachoman** [comment]
What is the output of `sudo grep -i -R noduplicates /etc/fail2ban`?

**Comment by Destarianon** [comment]
The output is completely blank.

**Comment by imthenachoman** [comment]
Humm. I am not sure why you are getting that error. I can' find anything in the docs or online. Try posting on https://askubuntu.com/. I will keep looking too.

**Comment by Destarianon** [comment]
I have worked around the issue by removing the [sshd] jail from the default configuration which seems to have cleared up the error, but doesn't really explain what caused it to begin with.

**Comment by imthenachoman** [comment]
Did you take a backup? What was in the [sshd] jail from the default configuration?

**Comment by celine168** [comment]
I know this is an old issue, but this is what it says in `etc/fail2ban/jail.d/defaults-debian.conf`:
```
[sshd]
enabled = true
```

**Comment by siebenbrunner** [comment]
fyi, I had the same issue, and simply changing `[sshd]` to `[ssh]` and then running `sudo fail2bain-client add ssh` fixed it. Also, I added the whole section in the `/etc/fail2ban/jail.local` file instead of creating a separate one.

**Comment by hellresistor** [comment]
I think Isn't needed add the sshd because are inside of jail.local file and/or /jail.d/defaults-debian.conf

**Comment by lgaida** [comment]
I'm setting up a server with on Debian 10 (Buster)
and i'm also getting `name 'noduplicates' is not defined`
after running `sudo fail2ban-client add sshd`

However `sudo fail2ban-client status` still lists sshd
and even `sudo fail2ban-client status sshd` prints the expected output as per README.md

As celine168 and hellresistor already said: looks like you don't have to add sshd on your own since it is enabled by default

**Comment by imthenachoman** [comment]
Closing as this issue seems resolved. Thanks!

**Comment by hellresistor** [comment]
have you run `sudo apt update && sudo apt install -y openssh-server` ?
