### ISSUE TITLE
hidepid=2 unsupported by systemd

### ISSUE THREAD

**Issue by nlgranger** [imthenachoman/How-To-Secure-A-Linux-Server#37]
Sadly, systemd seems to assume /proc is mounted with `hidepid` set to its default value in order to function properly.
See:
- https://bugzilla.redhat.com/show_bug.cgi?id=1130796
- https://lists.freedesktop.org/archives/systemd-devel/2012-October/006860.html

Considering the widespread use of systemd nowadays, I suppose you might want to add a notice for its user.

**Comment by imthenachoman** [comment]
Will do. Just started a new job so a little behind with updates but will get to it soon. Thanks!

**Comment by imthenachoman** [comment]
So it seems to be working fine on my machine but I will add a note. Thanks!

**Comment by imthenachoman** [comment]
Has it broken anything for you? I just redid my server and so far haven't had any issues with `hidepid`. Wondering if they fixed the bug?

**Comment by DonPicciotto** [comment]
> 
> 
> Has it broken anything for you? I just redid my server and so far haven't had any issues with `hidepid`. Wondering if they fixed the bug?

It broke something for me, my pi-hole FTL stop working if I mount /proc with hidepid

**Comment by maverickg59** [comment]
Here's a nifty explanation from the Red Hat Customer Portal on why mounting /proc on `hidepid=2` isn't a great idea in RHEL 7+. They do mention that eventually it may become an option.

[https://access.redhat.com/solutions/6704531](https://access.redhat.com/solutions/6704531)
