### ISSUE TITLE
How to find any duplicate parameter in /etc/ssh/sshd_config

### ISSUE THREAD

**Issue by than0s** [imthenachoman/How-To-Secure-A-Linux-Server#38]
On step 2 of [Secure /etc/ssh/sshd_config](https://github.com/imthenachoman/How-To-Secure-A-Linux-Server#secure-etcsshsshd_config), a quick and dirty way to find any duplicate parameter is with: 

`awk '{print $1}' /etc/ssh/sshd_config | sort | uniq -c | grep -v ' 1 ' `

**Comment by imthenachoman** [comment]
Nice! I will add this when I get a chance. A little caught up with a new job.

**Comment by imthenachoman** [comment]
Adding this. Thanks!
