### ISSUE TITLE
Suggestion: Add step for ensuring that a password is required for sudo

### ISSUE THREAD

**Issue by sbrl** [imthenachoman/How-To-Secure-A-Linux-Server#39]
In some distributions such as _Raspbian_, by default a password is not required to use `sudo`. Obviously this is no good - so I suggest adding a step to ensure that a password is required.

This can be done like so, at least in Raspbian:

```bash
sudoedit /etc/sudoers.d/010_pi-nopasswd
```

Then remove the `NO` prefix to `NOPASSWD`, then save & exit.

**Comment by imthenachoman** [comment]
Thanks. I will add this when I get a moment.

**Comment by daxmc99** [comment]
Also would like this due to the _Raspbian_ default not requiring sudo
