### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by PaS3** [imthenachoman/How-To-Secure-A-Linux-Server#47]
I found this link and testing it with my system     https://www.cyberciti.biz/faq/linux-kernel-etcsysctl-conf-security-hardening/

Also there is Lynis  which has built in/updated filters for sysctl testing          https://cisofy.com/lynis/

**Comment by imthenachoman** [comment]
Thanks. I talk about Lynis in my article. I will add the other one. Thanks!
