### ISSUE TITLE
Guide for LXD

### ISSUE THREAD

**Issue by elesiuta** [imthenachoman/How-To-Secure-A-Linux-Server#59]
I recently put together some notes for myself for using LXD, if there's interest I can clean them up a bit more and make a pull request.

My reasons for using LXD came down to:
- Don't need the scaling capabilities of Docker
- Not all programs have trusted and well maintained Docker images available, and maintaining a pipeline to build your own is overkill for a personal home server
- LXD creates containers that are unprivileged by default and confined with [apparmor,](https://ubuntu.com/server/docs/containers-lxd) so it is relatively easy to do securely and only a few extra steps on top of installing packages normally
- You can setup [Docker inside of LXD for added security](https://unix.stackexchange.com/questions/254956/what-is-the-difference-between-docker-lxd-and-lxc)

My notes:
### Main references
- https://linuxcontainers.org/lxd/getting-started-cli/
- https://wiki.archlinux.org/index.php/LXD
- https://www.digitalocean.com/community/tutorials/how-to-set-up-and-use-lxd-on-ubuntu-16-04

### setup
sudo snap install lxd
lxd init
accept defaults to everything (don't need ip6 though, can disable later with lxc network set lxdbr0 ipv6.address none)

### create container
lxc launch ubuntu:20.04 \<container name\>

### disable autostart
lxc config set \<container name\> boot.autostart false

### list containers (note container ip, interface is the internal name inside container)
lxc list

### run commands in container or enter interactive shell
lxc exec \<container name\> -- [command to run in container]
lxc exec \<container name\> -- sudo --login --user ubuntu
lxc exec \<container name\> bash

### forward traffic
\<server local interface\> := probably enp34s0, check with 'ip link show' on host
\<server local ip\> := self explanatory
\<server port\> := port you want to forward from host to container
\<container ip:port\> := get ip from lxc list, port that is listening inside container
sudo iptables -t nat -I PREROUTING -i \<server local interface\> -p TCP -d \<server local ip\> --dport \<server port\> -j DNAT --to-destination \<container ip:port\> -m comment --comment "forward to container"

### list iptables rules
sudo iptables -t nat -L PREROUTING

### make rules persist across reboots
sudo apt install iptables-persistent
sudo netfilter-persistent save

### devices and mounts
https://www.cyberciti.biz/faq/how-to-add-or-mount-directory-in-lxd-linux-container/
https://askubuntu.com/questions/610513/how-do-i-share-a-directory-between-an-lxc-container-and-the-host
https://github.com/lxc/lxd#can-i-bind-mount-my-home-directory-in-a-container
https://github.com/lxc/lxd/blob/master/doc/userns-idmap.md
#### check devices
lxc config device show \<container name\>
#### mount (read only by default)
lxc config device add \<container name\> \<device name\> disk source=\<path on host\> path=\<path on container\>
#### mount (add write permission)
use command 'id' to check uid and gid on host and container (all probably 1000)
lxc config set \<container name\> raw.idmap "both 1000 1000"
#### remove mount
lxc config device remove \<container name\> \<device name\>

### restart container
lxc restart \<container name\>

### ways to check containers (and make sure they are unprivileged)
lxc config show --expanded \<container name\> | grep privileged
ps -ef | grep \<process in container\> # make sure not running as root
lxc config get \<container name\> security.privileged # If that shows "true", then the container is privileged, otherwise it is not
lxc list security.privileged=true # check all at once

**Comment by imthenachoman** [comment]
This is great. I will work to add it in. Might be a few as we just moved and I'm knee deep in unpacking.

**Comment by elesiuta** [comment]
Sounds good, a couple things I noticed/forgot to mention.

The mounts being read only or read/write depends on their owner and permissions which I usually set to 755. Another (probably simpler) way to get read only mounts is to use bind, then make that mount visible to the container.  
`sudo mount --bind -o ro /mnt/data /mnt/read_only_data`

The other thing is ufw doesn't start after a reboot if using netfilter-persistent (at least on ubuntu). The fix found [here](https://devtidbits.com/2019/07/31/ufw-service-not-loading-after-a-reboot/) is to add the line `After=netfilter-persistent.service` after `Before=network.target` in the file `/lib/systemd/system/ufw.service`

**Comment by elesiuta** [comment]
Another thing I found that might be of interest is that a compromised container could potentially do MAC or IP spoofing on the bridge [(source)](https://linuxcontainers.org/lxd/docs/master/security)

To prevent this, you can enable MAC and IP filtering by running this command for every container (if you already ran your containers, it'll probably be assigned a new IP address, which you can also set yourself by setting ipv4.address on the eth0 device)  
`lxc config device override <container name> eth0 security.mac_filtering=true security.ipv4_filtering=true`

**Comment by imthenachoman** [comment]
Have you thought about creating a new guide just for LXD? I worry if we merge the two it might create confusion for folks who aren't using LXD? Thoughts?

**Comment by elesiuta** [comment]
> Have you thought about creating a new guide just for LXD? I worry if we merge the two it might create confusion for folks who aren't using LXD? Thoughts?

I was starting to work on one but stopped due to no longer using LXD myself and migrating my setup to use just docker.  

I also agree, combining LXD with this guide might create confusion for people who probably don't need LXD and just be too much. It's probably still worth mentioning along with AppArmor for people who wish to go that route and that's it. I think you took a good approach by sticking to the base OS and this is a great guide as it is.

**Comment by imthenachoman** [comment]
Thank you!

**Comment by elesiuta** [comment]
I think we can close this issue now, I was going to add a couple links mentioning this to the AppArmor section, but since it hasn't been written yet and I'm not familiar enough to write anything on it, I'll just leave it up to whoever does to decide if they want to mention this.

- [LXD Guide (unprivileged and uses AppArmor by default)](https://discourse.ubuntu.com/t/containers-lxd/11525) (this one goes a bit more in depth in some areas I didn't mention)
- [AppArmor profiles for Docker](https://docs.docker.com/engine/security/apparmor/)
- [Run Docker in rootless mode](https://docs.docker.com/engine/security/rootless/) (alternative to using AppArmor to mitigate some potential vulnerabilities)
- [Podman compose](https://github.com/containers/podman-compose) (drop-in replacement for docker compose with goal of being rootless)
