### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by ahangarha** [imthenachoman/How-To-Secure-A-Linux-Server#6]
Hi

May you please publish this valuable document Under some copyleft and specially Free Culture license (such as CC0, CC-BY, CC-BY-SA)?

**Comment by imthenachoman** [comment]
Hello. I do not know a lot about copyrights. I have never heard of copyleft or any of the others you mentioned. I will do some digging. If you have any advice or helpful articles I can read please share. 

And would a guide like this need to be copyrighted? It's all information publicly available.

**Comment by ahangarha** [comment]
I do suggest you to have a look on https://creativecommons.org/ for more information on copyleft movement licenses for cultural works.

If you have no intention to copyright it and you have no issue providing it with zero restriction, you may go for `CC0` / public domain. Otherwise, I do suggest `CC-BY`.

Many people put copyright on what they make as remix of other existing works and close them by saying ALL RIGHTS RESERVED. We, who support free culture movement, believe in SOME RIGHTS RESERVED, with lesser right the better approach since we believe this would be better for having a more diverse and creative world.

**Comment by imthenachoman** [comment]
I will check into it. Thank you!

**Comment by rvdmei** [comment]
No legal advice, but be aware that in the current form the work is copyrighted and making any copies is a copyright violation in many countries. By adding a license you can grant others to use (copy / modify) the material. For an example of a license check https://creativecommons.org/licenses/by-sa/4.0/

**Comment by imthenachoman** [comment]
Why/how is it copyrighted in its current form? I didn't add any copyright, did I?

I could use some help with which license to use and how to apply it? I have those links and I will check them out when I have time but with a 2 year old its hard to find the time to read up on copyrighting. 

I don't want any copyright. I want folks to be able to do whatever they want with it, as long as I don't get in trouble for anything. It would be nice to get a link back or acknowledgement if thats an option. 

Any advice?

**Comment by imthenachoman** [comment]
So that website makes it pretty easy. I went through the https://creativecommons.org/choose/ wizard and ended up with CC-BY-NC-SA. Is that okay or is it too restrictive?

**Comment by rvdmei** [comment]
Copyright is (often) a right, you get it because you wrote it (provided you did). At least this is the case in many counties. In some situations you have to claim copyright, you have to figure out for yourself where / when. As for the license, the NC clause adds a restriction. Example: I can’t use the content in slides / docs at work, even if I attribute you as author. Typically you would see the NC clause applied to creative work (art, etc.).

**Comment by imthenachoman** [comment]
I added copyright info. Is it okay?

**Comment by rvdmei** [comment]
You should add the license text as a separate doc to the repo too. You can use the Add License button in GitHub to do this.

**Comment by imthenachoman** [comment]
Oh boy. They don't have the creative commons ones in their list. I guess I'll go with MIT - it seems to make the most sense...

**Comment by rvdmei** [comment]
You can always add the file yourself. Creative Commons website should have all the info on what to add.

**Comment by imthenachoman** [comment]
Added. Thanks!!
