### ISSUE TITLE
[Request] Setup A Website/Neocities Site

### ISSUE THREAD

**Issue by seniorm0ment** [imthenachoman/How-To-Secure-A-Linux-Server#60]
Suggesting setting up a backup website that doesn't require going through Github to view.
A free option being Neocities, at minimum this would be nice. Alternatively, a super basic pure HTML/CSS website that hosts this same content. If a website is not desired (although nice imo), a Gitea instance or some other self-hosted similar service would be very nice to have.

**Comment by imthenachoman** [comment]
I put it on GitHub so others can contribute to it. My hope was to make it so it would grow with user contributed ideas. Quite a few folks have contributed content.

**Comment by grravity** [comment]
Could you not mirror it elsewhere too is my suggestion?
It's good information

**Comment by imthenachoman** [comment]
I mean, I could, but why? What is wrong with GitHub?
