### ISSUE TITLE
psad: pid file /var/run/psad/psadwatchd.pid does not exist for psadwatchd on ...

### ISSUE THREAD

**Issue by sysadt** [imthenachoman/How-To-Secure-A-Linux-Server#61]
Hi,
I followed your guide and ran into the following problem when using `psad -R` : 
```
/etc/psad# ufw reload
Firewall reloaded
root@server:/etc/psad# psad -R
[-] psad: pid file /var/run/psad/psadwatchd.pid does not exist for psadwatchd on server
[+] Stopping psad, pid: 1491
[+] Stopping psad_fw_read, pid: 1492
[+] Restarting psad daemons on
```

**Comment by sysadt** [comment]
Nevermind this fixed it:
https://carteryagemann.com/psad-on-pi.html

**Comment by imthenachoman** [comment]
So it looks like you have to set another setting for `psadwatchd` to start. I will update the guide.

**Comment by DevLomoSE** [comment]
> This helped: https://carteryagemann.com/psad-on-pi.html
> But when using `psad -H` it still says `[-] psadwatchd daemon not running.`

in the config file adding (/etc/psad/psad.conf):
    ENABLE_PSADWATCHD Y;
and then follow the instructions at https://carteryagemann.com/psad-on-pi.html
worked for me

**Comment by imthenachoman** [comment]
Yup. I added the `ENABLE_PSADWATCHD` thing to my guide.

**Comment by faxotherapy** [comment]
HIi, I'm still having the “psad: psadwatchd is not running on” after I added “ENABLE_PSADWATCHD Y;” and followed the above guide.

**Comment by faxotherapy** [comment]
> I'm still having the “psad: psadwatchd is not running on” after I added “ENABLE_PSADWATCHD Y;”

_psadwatchd_ does indeed start and run, but stops running after a few seconds. Is it expected?

> psad --fw-analyze
[+] Parsing INPUT chain rules.
[+] Parsing INPUT chain rules.
[-] Errors found in firewall config.
    emailed to root@localhost
[+] Results in /var/log/psad/fw_check
[+] Exiting.

This is due to the fact I set `IPV6` to `no` in `/etc/default/ufw` file.
