### ISSUE TITLE
Ansible playbook

### ISSUE THREAD

**Issue by freqmand** [imthenachoman/How-To-Secure-A-Linux-Server#69]
the steps are quite long, especially if you need to do it with multiple servers. 
an Ansible playbook to auto secure the server will be really awesome.

**Comment by imthenachoman** [comment]
Yeah. I do not know or use Ansible. I only have one machine so for me it is something I only have to do once, when I set the machine up. Plus, doing it manually helps teach.

**Comment by imthenachoman** [comment]
Plus, I wanted the focus of the guide to be how to install a secure Linux server. You don't need Ansible for that. So I'd rather leave that to another guide for someone to do. I personally would like to see such a guide since I do not know how to use Ansible.

**Comment by freqmand** [comment]
what about a shell/bash script that automate steps for Debian ?

**Comment by imthenachoman** [comment]
Yeah, that could be done. I personally don't have a need for it. If I had time I might create one. But since I only reinstall once every two years, there wouldn't be much worth it for me.

**Comment by thibaultmol** [comment]
For anyone stumbling on this issue, it's been done by someone else and is linked in the official readme:
https://github.com/imthenachoman/How-To-Secure-A-Linux-Server#using-ansible-playbooks-to-secure-your-linux-server
