### ISSUE TITLE
Controversial, maybe mis/disinformational FUD blog about Linux's lack of security

### ISSUE THREAD

**Issue by danmanrana** [imthenachoman/How-To-Secure-A-Linux-Server#71]
Please pardon if this has been discussed before or if [this blog](https://drbobtechblog.com/linux-insecure-9-year-old-security-flaw-just-discovered/) has been debunked, but I'm asking just in case. I can remove this thread. Oddly enough, there is/was another article on it that outlines more of these perceived flaws but I can no longer find it. I bring this up in the first place just in case the blog points out things that we can 'patch' ourselves.

**Comment by imthenachoman** [comment]
The vulnerability is legit but for kernel versions 2.x to 4.8.3. Debian 11, for example, is using v5 of the kernel. So as long as you're on a newer/updated system you should be fine. Check what kernel version you are using.
