### ISSUE TITLE
SSHD Config UsePrivilegeSeparation

### ISSUE THREAD

**Issue by Ethaseo** [imthenachoman/How-To-Secure-A-Linux-Server#72]
I think the section about UsePrivilegeSeparation can be removed.
I couldnt find this option in the man pages.
According to [this](https://www.openssh.com/txt/release-7.5) release notes:

 * This release deprecates the sshd_config UsePrivilegeSeparation
   option, thereby making privilege separation mandatory. Privilege
   separation has been on by default for almost 15 years and
   sandboxing has been on by default for almost the last five.

**Comment by imthenachoman** [comment]
Thanks. I will check and update.

**Comment by imthenachoman** [comment]
I updated it. Thanks!
