### ISSUE TITLE
aide --init   ERROR: missing configuration

### ISSUE THREAD

**Issue by MNXOnline** [imthenachoman/How-To-Secure-A-Linux-Server#83]
When trying to follow the AIDE part of the tutorial, on Debian GNU/Linux 11 (bullseye), it gives an error because the configuration files are not created nor on /etc/default or /etc/aide. 
On Ubuntu's Help page, in this article, they suggest installign aide-common for 14.04+ versions of Ubuntu. 
With this package installed, I could continue with the guide. 
I hope this helps to improve the guide. 
Thanks for the nice job there!
Regards,
Mannix

**Comment by imthenachoman** [comment]
Added! Thanks!
