### ISSUE TITLE
Firewall rules

### ISSUE THREAD

**Issue by innoreq** [imthenachoman/How-To-Secure-A-Linux-Server#84]
First of all: great guide, I've always been looking for something like that!

In the firewall section, there are some rules mentioned, among others the http rules. I ran into a problem, because I skipped those initially, and got stuck then in the PASD section when trying to install that package. This could be fixed by adding the http rules.

So, perhaps the importance of those rules for the later progress should be mentioned, this could help other users.

**Comment by imthenachoman** [comment]
Do you mean in step 5 of https://github.com/imthenachoman/How-To-Secure-A-Linux-Server/blob/master/README.md#steps-13? 

I want to confirm with you before I add/update.

**Comment by innoreq** [comment]
Exactly!

**Comment by imthenachoman** [comment]
Added. Thanks!
