### ISSUE TITLE
Conflicting statements on CIS benchmarks

### ISSUE THREAD

**Issue by Bojan023** [imthenachoman/How-To-Secure-A-Linux-Server#97]
Firstly, thank you for trying to condense so much information out there. I think this is a perfect starting point for self-hosters at home.

However, within a couple of minutes reading there are two conflicting statements regarding CIS benchmarks:

https://github.com/imthenachoman/How-To-Secure-A-Linux-Server/blob/8f78e027e9b4e53deb81db669aef8c9ddd5ff1c2/README.md?plain=1#L108

https://github.com/imthenachoman/How-To-Secure-A-Linux-Server/blob/8f78e027e9b4e53deb81db669aef8c9ddd5ff1c2/README.md?plain=1#L259

The first recommends to follow this guide first and a CIS Benchmark afterwards. The latter one states the opposite. My suggestion is to stick to the first statement and thus alter the second statement.

**Comment by imthenachoman** [comment]
Thanks. I tweaked the verbiage. Is that better?
